version: "3.8"

services:
    chat_web:
        container_name: chat_web
        image: nginx:alpine
        ports:
            - "8060:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - chat_app
        networks:
            - chat_network

    chat_app:
        container_name: chat_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - chat_db
            - chat_redis
        volumes:
            - ./:/var/www
        networks:
            - chat_network
        ports:
            - "9080:9000"
        environment:
            APP_ENV: local
            DB_HOST: chat_db
            REDIS_HOST: chat_redis

    chat_db:
        container_name: chat_db
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - chat_database:/var/lib/mysql
        networks:
            - chat_network
        ports:
            - "3307:3306"

    chat_redis:
        container_name: chat_redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6378:6379"
        networks:
            - chat_network

    chat_node:
        container_name: chat_node
        image: node:alpine
        volumes:
            - ./:/var/www
        command: sh -c "npm install && npm run build"
        depends_on:
            - chat_app
        ports:
            - "8010:8000"
        networks:
            - chat_network

networks:
    chat_network:
        driver: bridge

volumes:
    chat_database:
